const PostalCodeDB = {
    PROVINCE_BY_LETTER: {
        'A': 'NL', 'B': 'NS', 'C': 'PE', 'E': 'NB',
        'G': 'QC', 'H': 'QC', 'J': 'QC',
        'K': 'ON', 'L': 'ON', 'M': 'ON', 'N': 'ON', 'P': 'ON',
        'R': 'MB', 'S': 'SK', 'T': 'AB', 'V': 'BC',
        'X': 'NT', 'Y': 'YT'
    },

    PROVINCE_NAMES: {
        'ON': 'Ontario', 'QC': 'Quebec', 'BC': 'British Columbia', 'AB': 'Alberta',
        'MB': 'Manitoba', 'SK': 'Saskatchewan', 'NS': 'Nova Scotia',
        'NB': 'New Brunswick', 'NL': 'Newfoundland and Labrador',
        'PE': 'Prince Edward Island', 'NT': 'Northwest Territories',
        'YT': 'Yukon', 'NU': 'Nunavut'
    },

    FSA_CITIES: {
        'K1A': ['Ottawa'], 'K1B': ['Ottawa'], 'K1C': ['Ottawa'], 'K1E': ['Ottawa'],
        'K1G': ['Ottawa'], 'K1H': ['Ottawa'], 'K1J': ['Ottawa'], 'K1K': ['Ottawa'],
        'K1L': ['Ottawa'], 'K1M': ['Ottawa'], 'K1N': ['Ottawa'], 'K1P': ['Ottawa'],
        'K1R': ['Ottawa'], 'K1S': ['Ottawa'], 'K1T': ['Ottawa'], 'K1V': ['Ottawa'],
        'K1W': ['Ottawa'], 'K1X': ['Ottawa'], 'K1Y': ['Ottawa'], 'K1Z': ['Ottawa'],
        'K2A': ['Ottawa'], 'K2B': ['Ottawa'], 'K2C': ['Ottawa'], 'K2E': ['Ottawa'],
        'K2G': ['Ottawa'], 'K2H': ['Ottawa'], 'K2J': ['Ottawa'], 'K2K': ['Ottawa'],
        'K2L': ['Ottawa'], 'K2M': ['Ottawa'], 'K2P': ['Ottawa'], 'K2R': ['Ottawa'],
        'K2S': ['Ottawa'], 'K2T': ['Ottawa'], 'K2V': ['Ottawa'], 'K2W': ['Ottawa'],
        'L1A': ['Peterborough'], 'L1B': ['Bowmanville'], 'L1C': ['Bowmanville'],
        'L1E': ['Markham'], 'L1G': ['Oshawa'], 'L1H': ['Oshawa'], 'L1J': ['Oshawa'],
        'L1K': ['Oshawa'], 'L1L': ['Oshawa'], 'L1M': ['Whitby'], 'L1N': ['Whitby'],
        'L1P': ['Whitby'], 'L1R': ['Whitby'], 'L1S': ['Pickering'], 'L1T': ['Pickering'],
        'L1V': ['Pickering'], 'L1W': ['Ajax'], 'L1X': ['Stouffville'], 'L1Z': ['Uxbridge'],
        'L3P': ['Markham'], 'L3R': ['Markham'], 'L3S': ['Markham'], 'L3T': ['Markham'],
        'L4B': ['Richmond Hill'], 'L4C': ['Richmond Hill'], 'L4E': ['Richmond Hill'],
        'L4H': ['Vaughan'], 'L4J': ['Vaughan'], 'L4K': ['Vaughan'], 'L4L': ['Vaughan'],
        'L4M': ['Sault Ste. Marie'], 'L4N': ['Barrie'], 'L4P': ['Newmarket'],
        'L4R': ['Barrie'], 'L4S': ['Newmarket'], 'L4T': ['Mississauga'],
        'L4V': ['Mississauga'], 'L4W': ['Mississauga'], 'L4X': ['Mississauga'],
        'L4Y': ['Mississauga'], 'L4Z': ['Mississauga'], 'L5A': ['Mississauga'],
        'L5B': ['Mississauga'], 'L5C': ['Mississauga'], 'L5E': ['Mississauga'],
        'L5H': ['Mississauga'], 'L5J': ['Mississauga'], 'L5K': ['Mississauga'],
        'L5L': ['Mississauga'], 'L5M': ['Mississauga'], 'L5N': ['Mississauga'],
        'L5R': ['Mississauga'], 'L5S': ['Mississauga'], 'L5T': ['Mississauga'],
        'L5V': ['Mississauga'], 'L5W': ['Mississauga'], 'L6A': ['Milton'],
        'L6B': ['Hamilton'], 'L6C': ['Hamilton'], 'L6E': ['Hamilton'],
        'L6G': ['Hamilton'], 'L6H': ['Hamilton'], 'L6J': ['Hamilton'],
        'L6K': ['Hamilton'], 'L6L': ['Hamilton'], 'L6M': ['Hamilton'],
        'L6P': ['Brampton'], 'L6R': ['Brampton'], 'L6S': ['Brampton'],
        'L6T': ['Brampton'], 'L6V': ['Brampton'], 'L6W': ['Brampton'],
        'L6X': ['Brampton'], 'L6Y': ['Brampton'], 'L6Z': ['Brampton'],
        'L7A': ['Georgetown'], 'L7B': ['Georgetown'], 'L7C': ['Oakville'],
        'L7E': ['Caledon'], 'L7G': ['Brampton'], 'L7J': ['Caledon'],
        'L7L': ['Oakville'], 'L7M': ['Oakville'], 'L7N': ['Burlington'],
        'L7P': ['Burlington'], 'L7R': ['Burlington'], 'L7S': ['Burlington'],
        'L7T': ['Burlington'], 'L7V': ['Burlington'], 'L7W': ['Burlington'],
        'L7X': ['Burlington'], 'L7Y': ['Burlington'], 'L7Z': ['Burlington'],
        'M1B': ['Toronto'], 'M1C': ['Toronto'], 'M1E': ['Toronto'],
        'M1G': ['Toronto'], 'M1H': ['Toronto'], 'M1J': ['Toronto'],
        'M1K': ['Toronto'], 'M1L': ['Toronto'], 'M1M': ['Toronto'],
        'M1N': ['Toronto'], 'M1P': ['Toronto'], 'M1R': ['Toronto'],
        'M1S': ['Toronto'], 'M1T': ['Toronto'], 'M1V': ['Toronto'],
        'M1W': ['Toronto'], 'M1X': ['Toronto'], 'M2N': ['Toronto'],
        'M2P': ['Toronto'], 'M2R': ['Toronto'], 'M3A': ['Toronto'],
        'M3B': ['Toronto'], 'M3C': ['Toronto'], 'M3H': ['Toronto'],
        'M3J': ['Toronto'], 'M3K': ['Toronto'], 'M3L': ['Toronto'],
        'M3M': ['Toronto'], 'M3N': ['Toronto'], 'M4A': ['Toronto'],
        'M4B': ['Toronto'], 'M4C': ['Toronto'], 'M4E': ['Toronto'],
        'M4G': ['Toronto'], 'M4H': ['Toronto'], 'M4J': ['Toronto'],
        'M4K': ['Toronto'], 'M4L': ['Toronto'], 'M4M': ['Toronto'],
        'M4N': ['Toronto'], 'M4P': ['Toronto'], 'M4R': ['Toronto'],
        'M4S': ['Toronto'], 'M4T': ['Toronto'], 'M4V': ['Toronto'],
        'M4W': ['Toronto'], 'M4X': ['Toronto'], 'M4Y': ['Toronto'],
        'M5A': ['Toronto'], 'M5B': ['Toronto'], 'M5C': ['Toronto'],
        'M5E': ['Toronto'], 'M5G': ['Toronto'], 'M5H': ['Toronto'],
        'M5J': ['Toronto'], 'M5K': ['Toronto'], 'M5L': ['Toronto'],
        'M5M': ['Toronto'], 'M5N': ['Toronto'], 'M5P': ['Toronto'],
        'M5R': ['Toronto'], 'M5S': ['Toronto'], 'M5T': ['Toronto'],
        'M5V': ['Toronto'], 'M5W': ['Toronto'], 'M5X': ['Toronto'],
        'M6A': ['Toronto'], 'M6B': ['Toronto'], 'M6C': ['Toronto'],
        'M6E': ['Toronto'], 'M6G': ['Toronto'], 'M6H': ['Toronto'],
        'M6J': ['Toronto'], 'M6K': ['Toronto'], 'M6L': ['Toronto'],
        'M6M': ['Toronto'], 'M6N': ['Toronto'], 'M6P': ['Toronto'],
        'M6R': ['Toronto'], 'M6S': ['Toronto'], 'M7A': ['Toronto'],
        'M7R': ['Mississauga'], 'M7V': ['Toronto'], 'M7W': ['Toronto'],
        'M8V': ['Toronto'], 'M8W': ['Toronto'], 'M8X': ['Toronto'],
        'M8Y': ['Toronto'], 'M8Z': ['Toronto'], 'N1A': ['Guelph'],
        'N1C': ['Guelph'], 'N1E': ['Guelph'], 'N1G': ['Guelph'],
        'N1H': ['Guelph'], 'N1L': ['Guelph'], 'N1R': ['Guelph'],
        'N1S': ['Guelph'], 'N1T': ['Guelph'], 'N2A': ['Kitchener'],
        'N2B': ['Kitchener'], 'N2C': ['Cambridge'], 'N2E': ['Kitchener'],
        'N2G': ['Guelph'], 'N2H': ['Kitchener'], 'N2J': ['Kitchener'],
        'N2K': ['Kitchener'], 'N2L': ['Kitchener'], 'N2M': ['Kitchener'],
        'N2N': ['Kitchener'], 'N2P': ['Kitchener'], 'N2R': ['Kitchener'],
        'N3A': ['Cambridge'], 'N3B': ['Cambridge'], 'N3C': ['Cambridge'],
        'N3P': ['Waterloo'], 'N3R': ['Waterloo'], 'N3S': ['Waterloo'],
        'N3T': ['Waterloo'], 'N3V': ['Waterloo'], 'N3W': ['Waterloo'],
        'N3X': ['Waterloo'], 'N3Y': ['Waterloo'], 'N3Z': ['Waterloo'],
        'N4S': ['Woodstock'], 'N4T': ['Woodstock'], 'N4V': ['Woodstock'],
        'N4W': ['Woodstock'], 'N5A': ['London'], 'N5C': ['London'],
        'N5H': ['London'], 'N5V': ['London'], 'N5W': ['London'],
        'N5X': ['London'], 'N5Y': ['London'], 'N5Z': ['London'],
        'N6A': ['London'], 'N6G': ['London'], 'N6H': ['London'],
        'N6K': ['London'], 'N6L': ['London'], 'N6M': ['London'],
        'N6N': ['London'], 'N6P': ['London'], 'N7A': ['Sarnia'],
        'N7L': ['Sarnia'], 'N7M': ['Sarnia'], 'N7S': ['Sarnia'],
        'N7T': ['Sarnia'], 'N7V': ['Sarnia'], 'N7W': ['Sarnia'],
        'N7X': ['Sarnia'], 'N7Y': ['Sarnia'], 'N7Z': ['Sarnia'],
        'N8A': ['Windsor'], 'N8B': ['Windsor'], 'N8C': ['Windsor'],
        'N8E': ['Windsor'], 'N8H': ['Windsor'], 'N8M': ['Windsor'],
        'N8N': ['Windsor'], 'N8P': ['Windsor'], 'N8R': ['Windsor'],
        'N8S': ['Windsor'], 'N8T': ['Windsor'], 'N8V': ['Windsor'],
        'N8W': ['Windsor'], 'N8X': ['Windsor'], 'N8Y': ['Windsor'],
        'N8Z': ['Windsor'], 'N9A': ['Windsor'], 'N9B': ['Windsor'],
        'N9C': ['Windsor'], 'N9V': ['Windsor'], 'N9Y': ['Windsor'],
        'P1A': ['North Bay'], 'P1B': ['North Bay'], 'P1C': ['North Bay'],
        'P1L': ['Bracebridge'], 'P1P': ['Bracebridge'], 'P2A': ['Sudbury'],
        'P2N': ['Sudbury'], 'P3A': ['Sudbury'], 'P3B': ['Sudbury'],
        'P3E': ['Sudbury'], 'P3G': ['Sudbury'], 'P3L': ['Sudbury'],
        'P3N': ['Sudbury'], 'P3P': ['Sudbury'], 'P3S': ['Sudbury'],
        'P3Y': ['Sudbury'], 'P4N': ['Timmins'], 'P4P': ['Timmins'],
        'P4R': ['Timmins'], 'P5A': ['Elliot Lake'], 'P5E': ['Sault Ste. Marie'],
        'P5N': ['Sault Ste. Marie'], 'P6A': ['Sault Ste. Marie'],
        'P6B': ['Sault Ste. Marie'], 'P7A': ['Thunder Bay'],
        'P7B': ['Thunder Bay'], 'P7C': ['Thunder Bay'],
        'P7E': ['Thunder Bay'], 'P7G': ['Thunder Bay'],
        'P7J': ['Thunder Bay'], 'P7K': ['Thunder Bay'],
        'R1A': ['Winnipeg'], 'R2H': ['Winnipeg'], 'R2J': ['Winnipeg'],
        'R2K': ['Winnipeg'], 'R2L': ['Winnipeg'], 'R2M': ['Winnipeg'],
        'R2N': ['Winnipeg'], 'R2P': ['Winnipeg'], 'R2R': ['Winnipeg'],
        'R2V': ['Winnipeg'], 'R2W': ['Winnipeg'], 'R2X': ['Winnipeg'],
        'R2Y': ['Winnipeg'], 'R2Z': ['Winnipeg'], 'R3A': ['Winnipeg'],
        'R3B': ['Winnipeg'], 'R3C': ['Winnipeg'], 'R3E': ['Winnipeg'],
        'R3G': ['Winnipeg'], 'R3H': ['Winnipeg'], 'R3J': ['Winnipeg'],
        'R3K': ['Winnipeg'], 'R3L': ['Winnipeg'], 'R3M': ['Winnipeg'],
        'R3N': ['Winnipeg'], 'R3P': ['Winnipeg'], 'R3R': ['Winnipeg'],
        'R3S': ['Winnipeg'], 'R3T': ['Winnipeg'], 'R3V': ['Winnipeg'],
        'R3W': ['Winnipeg'], 'R3X': ['Winnipeg'], 'R3Y': ['Winnipeg'],
        'S4A': ['Regina'], 'S4H': ['Regina'], 'S4J': ['Regina'],
        'S4K': ['Regina'], 'S4L': ['Regina'], 'S4M': ['Regina'],
        'S4N': ['Regina'], 'S4P': ['Regina'], 'S4R': ['Regina'],
        'S4S': ['Regina'], 'S4T': ['Regina'], 'S4V': ['Regina'],
        'S4W': ['Regina'], 'S4X': ['Regina'], 'S4Y': ['Regina'],
        'S4Z': ['Regina'], 'S6V': ['Saskatoon'], 'S6W': ['Saskatoon'],
        'S6X': ['Saskatoon'], 'S6Y': ['Saskatoon'], 'S7A': ['Saskatoon'],
        'S7H': ['Saskatoon'], 'S7J': ['Saskatoon'], 'S7K': ['Saskatoon'],
        'S7L': ['Saskatoon'], 'S7M': ['Saskatoon'], 'S7N': ['Saskatoon'],
        'S7P': ['Saskatoon'], 'S7R': ['Saskatoon'], 'S7S': ['Saskatoon'],
        'S7T': ['Saskatoon'], 'S7V': ['Saskatoon'], 'S7W': ['Saskatoon'],
        'S9A': ['Prince Albert'], 'S9H': ['Prince Albert'],
        'T1A': ['Calgary'], 'T1B': ['Red Deer'], 'T1C': ['Red Deer'],
        'T1E': ['Red Deer'], 'T1G': ['Red Deer'], 'T1H': ['Red Deer'],
        'T1J': ['Red Deer'], 'T1K': ['Red Deer'], 'T1L': ['Red Deer'],
        'T1M': ['Red Deer'], 'T1N': ['Red Deer'], 'T1P': ['Red Deer'],
        'T1R': ['Red Deer'], 'T1S': ['Red Deer'], 'T1T': ['Red Deer'],
        'T1V': ['Red Deer'], 'T1W': ['Red Deer'], 'T1X': ['Red Deer'],
        'T1Y': ['Red Deer'], 'T1Z': ['Red Deer'], 'T2A': ['Calgary'],
        'T2B': ['Calgary'], 'T2C': ['Calgary'], 'T2E': ['Calgary'],
        'T2G': ['Calgary'], 'T2H': ['Calgary'], 'T2J': ['Calgary'],
        'T2K': ['Calgary'], 'T2L': ['Calgary'], 'T2M': ['Calgary'],
        'T2N': ['Calgary'], 'T2P': ['Calgary'], 'T2R': ['Calgary'],
        'T2S': ['Calgary'], 'T2T': ['Calgary'], 'T2V': ['Calgary'],
        'T2W': ['Calgary'], 'T2X': ['Calgary'], 'T2Y': ['Calgary'],
        'T2Z': ['Calgary'], 'T3A': ['Calgary'], 'T3B': ['Calgary'],
        'T3C': ['Calgary'], 'T3E': ['Calgary'], 'T3G': ['Calgary'],
        'T3H': ['Calgary'], 'T3J': ['Calgary'], 'T3K': ['Calgary'],
        'T3L': ['Calgary'], 'T3M': ['Calgary'], 'T3N': ['Calgary'],
        'T3P': ['Calgary'], 'T3R': ['Calgary'], 'T3S': ['Calgary'],
        'T3Z': ['Calgary'], 'T4A': ['Lethbridge'], 'T4B': ['Lethbridge'],
        'T4C': ['Lethbridge'], 'T4E': ['Lethbridge'], 'T4N': ['Lethbridge'],
        'T4P': ['Lethbridge'], 'T4R': ['Lethbridge'], 'T4S': ['Lethbridge'],
        'T4T': ['Lethbridge'], 'T4V': ['Lethbridge'], 'T4W': ['Lethbridge'],
        'T4X': ['Lethbridge'], 'T4Y': ['Lethbridge'], 'T4Z': ['Lethbridge'],
        'T5A': ['Edmonton'], 'T5B': ['Edmonton'], 'T5C': ['Edmonton'],
        'T5E': ['Edmonton'], 'T5G': ['Edmonton'], 'T5H': ['Edmonton'],
        'T5J': ['Edmonton'], 'T5K': ['Edmonton'], 'T5L': ['Edmonton'],
        'T5M': ['Edmonton'], 'T5N': ['Edmonton'], 'T5P': ['Edmonton'],
        'T5R': ['Edmonton'], 'T5S': ['Edmonton'], 'T5T': ['Edmonton'],
        'T5V': ['Edmonton'], 'T5W': ['Edmonton'], 'T5X': ['Edmonton'],
        'T5Y': ['Edmonton'], 'T5Z': ['Edmonton'], 'T6A': ['Edmonton'],
        'T6B': ['Edmonton'], 'T6C': ['Edmonton'], 'T6E': ['Edmonton'],
        'T6G': ['Edmonton'], 'T6H': ['Edmonton'], 'T6J': ['Edmonton'],
        'T6K': ['Edmonton'], 'T6L': ['Edmonton'], 'T6M': ['Edmonton'],
        'T6N': ['Edmonton'], 'T6P': ['Edmonton'], 'T6R': ['Edmonton'],
        'T6S': ['Edmonton'], 'T6T': ['Edmonton'], 'T6V': ['Edmonton'],
        'T6W': ['Edmonton'], 'T6X': ['Edmonton'], 'T7A': ['Spruce Grove'],
        'T7S': ['Stony Plain'], 'T7X': ['Leduc'], 'T8A': ['Fort Saskatchewan'],
        'T8B': ['Fort Saskatchewan'], 'T8C': ['St. Albert'],
        'T8N': ['St. Albert'], 'T8R': ['St. Albert'], 'T8T': ['Spruce Grove'],
        'T8V': ['Spruce Grove'], 'T8W': ['Spruce Grove'], 'T8X': ['Spruce Grove'],
        'T9A': ['Grande Prairie'], 'T9C': ['Grande Prairie'],
        'V1A': ['Cranbrook'], 'V1B': ['Cranbrook'], 'V1C': ['Cranbrook'],
        'V1G': ['Campbell River'], 'V1H': ['Campbell River'],
        'V1J': ['Campbell River'], 'V1K': ['Campbell River'],
        'V1L': ['Nanaimo'], 'V1M': ['Nanaimo'], 'V1N': ['Nanaimo'],
        'V1P': ['Nanaimo'], 'V1R': ['Nanaimo'], 'V1S': ['Nanaimo'],
        'V1T': ['Nanaimo'], 'V1V': ['Nanaimo'], 'V1W': ['Nanaimo'],
        'V1X': ['Nanaimo'], 'V1Y': ['Nanaimo'], 'V1Z': ['Nanaimo'],
        'V2A': ['Penticton'], 'V2B': ['Penticton'], 'V2C': ['Penticton'],
        'V2E': ['Penticton'], 'V2G': ['Prince George'],
        'V2H': ['Prince George'], 'V2J': ['Prince George'],
        'V2K': ['Prince George'], 'V2L': ['Prince George'],
        'V2M': ['Prince George'], 'V2N': ['Prince George'],
        'V2P': ['Prince George'], 'V2R': ['Prince George'],
        'V2S': ['Prince George'], 'V2T': ['Prince George'],
        'V2V': ['Prince George'], 'V2W': ['Prince George'],
        'V2X': ['Prince George'], 'V2Y': ['Prince George'],
        'V2Z': ['Prince George'], 'V3A': ['Port Coquitlam'],
        'V3B': ['Port Coquitlam'], 'V3C': ['Port Coquitlam'],
        'V3E': ['Port Moody'], 'V3G': ['Langley'], 'V3H': ['Langley'],
        'V3J': ['Langley'], 'V3K': ['Langley'], 'V3L': ['Langley'],
        'V3M': ['Langley'], 'V3N': ['Langley'], 'V3P': ['Langley'],
        'V3R': ['Langley'], 'V3S': ['Langley'], 'V3T': ['Langley'],
        'V3V': ['Langley'], 'V3W': ['Langley'], 'V3X': ['Langley'],
        'V3Y': ['Langley'], 'V3Z': ['Langley'], 'V5A': ['Burnaby'],
        'V5B': ['Burnaby'], 'V5C': ['Burnaby'], 'V5E': ['Burnaby'],
        'V5G': ['Burnaby'], 'V5H': ['Burnaby'], 'V5J': ['Burnaby'],
        'V5K': ['Burnaby'], 'V5L': ['Burnaby'], 'V5M': ['Burnaby'],
        'V5N': ['Burnaby'], 'V5P': ['Burnaby'], 'V5R': ['Burnaby'],
        'V5S': ['Burnaby'], 'V5T': ['Burnaby'], 'V5V': ['Burnaby'],
        'V5W': ['Burnaby'], 'V5X': ['Burnaby'], 'V5Y': ['Burnaby'],
        'V5Z': ['Burnaby'], 'V6A': ['Vancouver'], 'V6B': ['Vancouver'],
        'V6C': ['Vancouver'], 'V6E': ['Vancouver'], 'V6G': ['Vancouver'],
        'V6H': ['Vancouver'], 'V6J': ['Vancouver'], 'V6K': ['Vancouver'],
        'V6L': ['Vancouver'], 'V6M': ['Vancouver'], 'V6N': ['Vancouver'],
        'V6P': ['Vancouver'], 'V6R': ['Vancouver'], 'V6S': ['Vancouver'],
        'V6T': ['Vancouver'], 'V6V': ['Vancouver'], 'V6W': ['Vancouver'],
        'V6X': ['Vancouver'], 'V6Y': ['Vancouver'], 'V6Z': ['Vancouver'],
        'V7A': ['North Vancouver'], 'V7B': ['North Vancouver'],
        'V7C': ['North Vancouver'], 'V7E': ['North Vancouver'],
        'V7G': ['North Vancouver'], 'V7H': ['North Vancouver'],
        'V7J': ['West Vancouver'], 'V7K': ['West Vancouver'],
        'V7L': ['West Vancouver'], 'V7M': ['West Vancouver'],
        'V7N': ['West Vancouver'], 'V7P': ['West Vancouver'],
        'V7R': ['West Vancouver'], 'V7S': ['West Vancouver'],
        'V7T': ['West Vancouver'], 'V7V': ['West Vancouver'],
        'V7W': ['West Vancouver'], 'V7X': ['West Vancouver'],
        'V7Y': ['West Vancouver'], 'V7Z': ['West Vancouver'],
        'V8A': ['Richmond'], 'V8B': ['Richmond'], 'V8C': ['Richmond'],
        'V8E': ['Richmond'], 'V8G': ['Richmond'], 'V8H': ['Richmond'],
        'V8J': ['Richmond'], 'V8K': ['Richmond'], 'V8L': ['Richmond'],
        'V8M': ['Richmond'], 'V8N': ['Richmond'], 'V8P': ['Richmond'],
        'V8R': ['Richmond'], 'V8S': ['Richmond'], 'V8T': ['Richmond'],
        'V8V': ['Richmond'], 'V8W': ['Richmond'], 'V8X': ['Richmond'],
        'V8Y': ['Richmond'], 'V8Z': ['Richmond'], 'V9A': ['Victoria'],
        'V9B': ['Victoria'], 'V9C': ['Victoria'], 'V9E': ['Victoria'],
        'V9G': ['Victoria'], 'V9H': ['Victoria'], 'V9J': ['Victoria'],
        'V9K': ['Victoria'], 'V9L': ['Victoria'], 'V9M': ['Victoria'],
        'V9N': ['Victoria'], 'V9P': ['Victoria'], 'V9R': ['Victoria'],
        'V9S': ['Victoria'], 'V9T': ['Victoria'], 'V9V': ['Victoria'],
        'V9W': ['Victoria'], 'V9X': ['Victoria'], 'V9Y': ['Victoria'],
        'V9Z': ['Victoria']
    },

    validateFormat(postalCode) {
        const cleaned = postalCode.replace(/\s/g, '').toUpperCase();
        if (!/^[A-Z]\d[A-Z]\d[A-Z]\d$/.test(cleaned)) {
            return { valid: false, error: 'Please enter a valid Canadian postal code (e.g. A1A 1A1)' };
        }
        return { valid: true, cleaned };
    },

    getProvinceFromPostalCode(postalCode) {
        const letter = postalCode.charAt(0).toUpperCase();
        return this.PROVINCE_BY_LETTER[letter] || null;
    },

    getCitiesFromFSA(postalCode) {
        const fsa = postalCode.replace(/\s/g, '').substring(0, 3).toUpperCase();
        return this.FSA_CITIES[fsa] || [];
    },

    validate(postalCode, province, city) {
        const formatCheck = this.validateFormat(postalCode);
        if (!formatCheck.valid) return formatCheck;

        const cleaned = formatCheck.cleaned;
        const expectedProvince = this.getProvinceFromPostalCode(cleaned);
        if (expectedProvince && province && expectedProvince !== province) {
            const pcProvince = this.PROVINCE_NAMES[expectedProvince] || expectedProvince;
            return { valid: false, error: `Postal code ${cleaned} belongs to ${pcProvince}, not the selected province` };
        }

        if (city) {
            const validCities = this.getCitiesFromFSA(cleaned);
            if (validCities.length > 0) {
                const cityLower = city.trim().toLowerCase();
                const matched = validCities.some(c => c.toLowerCase() === cityLower);
                if (!matched) {
                    return { valid: false, error: `Postal code ${cleaned} is typically in ${validCities.join(', ')}, not "${city}". Please verify your city.` };
                }
            }
        }

        return { valid: true, cleaned };
    }
};
